<?php

namespace Omnipay\Easytransac\Message;

use Omnipay\Common\Exception\InvalidRequestException;

class PurchaseRequest extends AbstractRequest
{
    /**
     * @throws InvalidRequestException
     */
    public function getData(): array
{
    $data = [
        'Amount' => $this->getAmount(),
        'ClientIp' => $this->getClientIp(),
        'OrderId' => $this->getTransactionId(),
        'Description' => $this->getDescription(),
        'Firstname' => $this->getCard()->getFirstName(),
        'Lastname' => $this->getCard()->getLastName(),
        'Email' => $this->getCard()->getEmail(),
        'Address' => $this->getCard()->getBillingAddress1(),
        'ZipCode' => $this->getCard()->getBillingPostcode(),
        'City' => $this->getCard()->getCity(),
        'Country' => $this->convertCountryToIso3($this->getCard()->getCountry()),
        'CallingCode' => $this->getCard()->getBillingPhoneExtension(),
        'Phone' => $this->getCard()->getBillingPhone(),
        'BirthDate' => $this->getCard()->getBirthday('Y-m-d'),
        '3DS' => $this->get3DS(),
        'CardNumber' => $this->getCard()->getNumber(),
        'CardYear' => $this->getCard()->getExpiryYear(),
        'CardMonth' => sprintf('%02d', $this->getCard()->getExpiryMonth()),
        'CardCVV' => $this->getCard()->getCvv(),
        'ReturnUrl' => $this->getReturnUrl(),
    ];

    $data['Signature'] = $this->getSignature($data);

    $this->validate('amount', 'clientIp', 'card');

    return $data;
}

    public function getEndpoint(): string
    {
        return $this->endpoint . '/payment/direct';
    }

    protected function createResponse($data): PurchaseResponse
    {
        return $this->response = new PurchaseResponse($this, $data);
    }

  protected function convertCountryToIso3(?string $country): string
  {
    $country = strtoupper(trim((string) $country));
    
    $map = [
         "AF" => "AFG",
    "AL" => "ALB",
    "DZ" => "DZA",
    "AS" => "ASM",
    "AD" => "AND",
    "AO" => "AGO",
    "AI" => "AIA",
    "AQ" => "ATA",
    "AG" => "ATG",
    "AR" => "ARG",
    "AM" => "ARM",
    "AX" => "ALA",
    "AW" => "ABW",
    "AU" => "AUS",
    "AT" => "AUT",
    "AZ" => "AZE",
    "BQ" => "BES",
    "BS" => "BHS",
    "BH" => "BHR",
    "BD" => "BGD",
    "BB" => "BRB",
    "BY" => "BLR",
    "BE" => "BEL",
    "BZ" => "BLZ",
    "BL" => "BLM",
    "BJ" => "BEN",
    "BM" => "BMU",
    "BT" => "BTN",
    "BO" => "BOL",
    "BA" => "BIH",
    "BW" => "BWA",
    "BV" => "BVT",
    "BR" => "BRA",
    "IO" => "IOT",
    "BN" => "BRN",
    "BG" => "BGR",
    "BF" => "BFA",
    "BI" => "BDI",
    "KH" => "KHM",
    "CM" => "CMR",
    "CA" => "CAN",
    "CV" => "CPV",
    "KY" => "CYM",
    "CF" => "CAF",
    "TD" => "TCD",
    "CL" => "CHL",
    "CN" => "CHN",
    "CX" => "CXR",
    "CC" => "CCK",
    "CO" => "COL",
    "KM" => "COM",
    "CG" => "COG",
    "CD" => "COD",
    "CK" => "COK",
    "CR" => "CRI",
    "CI" => "CIV",
    "HR" => "HRV",
    "CU" => "CUB",
    "CY" => "CYP",
    "CZ" => "CZE",
    "DK" => "DNK",
    "DJ" => "DJI",
    "DM" => "DMA",
    "DO" => "DOM",
    "TP" => "TMP",
    "EC" => "ECU",
    "EG" => "EGY",
    "SV" => "SLV",
    "GQ" => "GNQ",
    "ER" => "ERI",
    "EE" => "EST",
    "ET" => "ETH",
    "FK" => "FLK",
    "FO" => "FRO",
    "FJ" => "FJI",
    "FI" => "FIN",
    "FR" => "FRA",
    "FX" => "FXX",
    "GF" => "GUF",
    "PF" => "PYF",
    "TF" => "ATF",
    "GA" => "GAB",
    "GM" => "GMB",
    "GE" => "GEO",
    "DE" => "DEU",
    "GG" => "GGY",
    "GH" => "GHA",
    "GI" => "GIB",
    "GR" => "GRC",
    "GL" => "GRL",
    "GD" => "GRD",
    "GP" => "GLP",
    "GU" => "GUM",
    "GT" => "GTM",
    "GN" => "GIN",
    "GW" => "GNB",
    "GY" => "GUY",
    "HT" => "HTI",
    "HM" => "HMD",
    "VA" => "VAT",
    "HN" => "HND",
    "HK" => "HKG",
    "HU" => "HUN",
    "IM" => "IMN",
    "IS" => "ISL",
    "IN" => "IND",
    "ID" => "IDN",
    "IR" => "IRN",
    "IQ" => "IRQ",
    "IE" => "IRL",
    "IL" => "ISR",
    "IT" => "ITA",
    "JM" => "JAM",
    "JE" => "JEY",
    "JP" => "JPN",
    "JO" => "JOR",
    "KZ" => "KAZ",
    "KE" => "KEN",
    "KI" => "KIR",
    "KP" => "PRK",
    "KR" => "KOR",
    "KW" => "KWT",
    "KG" => "KGZ",
    "LA" => "LAO",
    "LV" => "LVA",
    "LB" => "LBN",
    "LS" => "LSO",
    "LR" => "LBR",
    "LY" => "LBY",
    "LI" => "LIE",
    "LT" => "LTU",
    "LU" => "LUX",
    "MO" => "MAC",
    "MF" => "MAF",
    "MK" => "MKD",
    "MG" => "MDG",
    "MW" => "MWI",
    "MY" => "MYS",
    "MV" => "MDV",
    "ML" => "MLI",
    "MT" => "MLT",
    "MH" => "MHL",
    "MQ" => "MTQ",
    "MR" => "MRT",
    "MU" => "MUS",
    "YT" => "MYT",
    "MX" => "MEX",
    "FM" => "FSM",
    "MD" => "MDA",
    "MC" => "MCO",
    "MN" => "MNG",
    "ME" => "MNE",
    "MS" => "MSR",
    "MA" => "MAR",
    "MZ" => "MOZ",
    "MM" => "MMR",
    "NA" => "NAM",
    "NR" => "NRU",
    "NP" => "NPL",
    "NL" => "NLD",
    "AN" => "ANT",
    "NC" => "NCL",
    "NZ" => "NZL",
    "NI" => "NIC",
    "NE" => "NER",
    "NG" => "NGA",
    "NU" => "NIU",
    "NF" => "NFK",
    "MP" => "MNP",
    "NO" => "NOR",
    "OM" => "OMN",
    "PK" => "PAK",
    "PW" => "PLW",
    "PA" => "PAN",
    "PG" => "PNG",
    "PY" => "PRY",
    "PE" => "PER",
    "PH" => "PHL",
    "PN" => "PCN",
    "PL" => "POL",
    "PS" => "PSE",
    "PT" => "PRT",
    "PR" => "PRI",
    "QA" => "QAT",
    "QZ" => "QZZ",
    "RE" => "REU",
    "RO" => "ROU",
    "RU" => "RUS",
    "RW" => "RWA",
    "KN" => "KNA",
    "LC" => "LCA",
    "VC" => "VCT",
    "WS" => "WSM",
    "SM" => "SMR",
    "ST" => "STP",
    "SA" => "SAU",
    "SN" => "SEN",
    "RS" => "SRB",
    "SC" => "SYC",
    "SL" => "SLE",
    "SG" => "SGP",
    "SK" => "SVK",
    "SI" => "SVN",
    "SB" => "SLB",
    "SO" => "SOM",
    "ZA" => "ZAF",
    "SS" => "SSD",
    "GS" => "SGS",
    "ES" => "ESP",
    "LK" => "LKA",
    "SH" => "SHN",
    "PM" => "SPM",
    "SD" => "SDN",
    "SR" => "SUR",
    "SX" => "SXM",
    "SJ" => "SJM",
    "SZ" => "SWZ",
    "SE" => "SWE",
    "CH" => "CHE",
    "SY" => "SYR",
    "TW" => "TWN",
    "TJ" => "TJK",
    "TZ" => "TZA",
    "TH" => "THA",
    "TG" => "TGO",
    "TK" => "TKL",
    "TL" => "TLS",
    "TO" => "TON",
    "TT" => "TTO",
    "TN" => "TUN",
    "TR" => "TUR",
    "TM" => "TKM",
    "TC" => "TCA",
    "TV" => "TUV",
    "UG" => "UGA",
    "UA" => "UKR",
    "AE" => "ARE",
    "GB" => "GBR",
    "US" => "USA",
    "UM" => "UMI",
    "UY" => "URY",
    "UZ" => "UZB",
    "VU" => "VUT",
    "VE" => "VEN",
    "VN" => "VNM",
    "VG" => "VGB",
    "VI" => "VIR",
    "WF" => "WLF",
    "EH" => "ESH",
    "YE" => "YEM",
    "ZM" => "ZMB",
    "ZW" => "ZWE",
    "CW" => "CUW",
    "KS" => "RKS",
    "ZZ" => "ZZZ"
    ];

    if (isset($map[$country])) {
        return $map[$country];
    }

    if (strlen($country) === 3) {
        return $country;
    }

    return $country;
}
}
